daemonset:
  enabled: true

resources:
  requests:
    cpu: "100m"
    memory: "300Mi"
  limits:
    memory: "400Mi"
# Filebeat main config
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata: {}
    

    output.elasticsearch:
      hosts: ["https://elasticsearch-master.elastic-stack.svc.cluster.local:9200"]
      username: "elastic"
      password: "admin"
      # If self-signed HTTPS and you want to skip verification (not for prod):
      ssl.verification_mode: none

# Mount container log paths (chart defaults are fine, leaving here for clarity)
#extraVolumes:
#  - name: varlibdockercontainers
#    hostPath:
#      path: /var/lib/docker/containers
#  - name: varlog
#    hostPath:
#      path: /var/log
#extraVolumeMounts:
#  - name: varlibdockercontainers
#    mountPath: /var/lib/docker/containers
#    readOnly: true
#  - name: varlog
#    mountPath: /var/log
#    readOnly: true
