admin_public_ip: "192.168.0.28"

user_name: ansible
user_public_key: "{{lookup('file', (playbook_dir, '..', 'project4-key.pub') | path_join | realpath) }}"

bastion_group_name: "bastion"
master_group_name: "master"
worker_group_name: "worker"


node_CDIR: "192.168.0.0/24"
bastion_private_ip: "192.168.0.32"
bastion_public_ip: "192.168.0.32"
master_private_ip: "192.168.0.30"
worker_private_ip: "192.168.0.31"

sshd_port: 22
nginx_ingress_port: 32080
prometheus_port: 32090
elasticsearch_port: 30920
grafana_port: 8080


master_reserved_ports: "2379,2380,6443,10250,{{sshd_port}}"
worker_reserved_ports: "10250,{{sshd_port}},{{nginx_ingress_port}},{{prometheus_port}},{{elasticsearch_port}}"

#Grafana related paramaters
container_name: "grafana"
prometheus_url: "{{worker_private_ip}}:{{prometheus_port}}"
elasticsearch_url: "{{worker_private_ip}}:{{elasticsearch_port}}"

calico_pod_cidr: "172.17.0.0/24"
calico_node_cidr: "192.168.0.0/24"

#Version of calico network
calico_version: "v3.30.3"
kubeadm_version: "v1.34"


