- name: Generate Bastion Firewall Template
  ansible.builtin.template:
    src: bastion-firewall.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
  when: bastion_group_name in group_names


- name: Generate Master Firewall Template
  ansible.builtin.template:
    src: master-firewall.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
  when: master_group_name in group_names


- name: Generate Worker Firewall Template
  ansible.builtin.template:
    src: worker-firewall.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
  when: worker_group_name in group_names
