version: 3

images:
  base_image:
    name: "quay.io/ansible/creator-ee:latest"

dependencies:
  system: system-req.txt
  python: python-req.txt
  galaxy: galaxy-req.yaml


options:
  package_manager_path: /usr/bin/microdnf
